# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20906bb81a24b53430653f0497c61295747ed14f379858385c793658d01a0e7976c590c86f2f8ab128be15af9a9ea9fd1bcefed1b59e12a881ebc34d09d2515c

test:
  secret_key_base: 451d6713aeb209b6efd8af3681ebdb4a0d85999dcf9e6a883b23ef18aea25b8dbf13c2dda1f4c31b2ff0f444a36abf6443b6ba73dc2a7a8e600e9e388617451b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
